version: '3.8'

services:
  web:
    build:
      context: .
      network: host
    container_name: mushroomie_web
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
