"""Reviewed prose replacements for section 3.3.3 of the Mushroomie ASM."""

# Each entry was reviewed against the supplied Mushroomie ASM. The mappings are
# deliberately explicit: no keyword-based rewriting is applied to the document.
PARAGRAPH_REWRITES: dict[str, str] = {
    "Trong hệ thống truyền thông số của Mushroomie, website là kênh sở hữu giữ vai trò trung tâm trong việc cung cấp thông tin thương hiệu, trưng bày sản phẩm, tiếp nhận nhu cầu tư vấn và hỗ trợ chuyển đổi đơn hàng. Quá trình triển khai được phân chia thành bốn giai đoạn trong kế hoạch ASM gồm chuẩn bị/tối ưu, triển khai nội dung, chạy quảng cáo và tổng hợp - đánh giá. Mỗi giai đoạn được đối chiếu với minh chứng thực tế, nhận định phân tích và tiêu chí đánh giá tương ứng.":
        "Trong hệ thống truyền thông số của Mushroomie, Website là kênh sở hữu trung tâm, thực hiện các chức năng cung cấp thông tin thương hiệu, trưng bày sản phẩm, tiếp nhận nhu cầu tư vấn và hỗ trợ chuyển đổi đơn hàng. Nhóm triển khai kênh này theo bốn giai đoạn của kế hoạch ASM, bao gồm chuẩn bị/tối ưu, triển khai nội dung, chạy quảng cáo và tổng hợp - đánh giá. Ở từng giai đoạn, kết quả được đối chiếu với minh chứng thực tế và tiêu chí đánh giá tương ứng.",
    "Về phạm vi nội dung, website sử dụng tên miền mushroomie.io.vn và tập trung vào các nhóm sản phẩm vòng tay, móc khóa, hộp quà, vòng cổ và quà tặng handmade. Ba giá trị thủ công, cảm xúc và trải nghiệm tặng quà được duy trì như các trục định vị xuyên suốt, phù hợp với thông điệp thương hiệu: 'Từ từng hạt nhỏ, tạo phong cách riêng.'":
        "Về phạm vi triển khai, Website sử dụng tên miền mushroomie.io.vn và giới thiệu các nhóm sản phẩm gồm vòng tay, móc khóa, hộp quà, vòng cổ và quà tặng handmade. Nội dung trên kênh được xây dựng nhất quán theo ba giá trị định vị là tính thủ công, cảm xúc và trải nghiệm tặng quà, qua đó thể hiện thông điệp thương hiệu: 'Từ từng hạt nhỏ, tạo phong cách riêng.'",
    "Từ góc độ nhận diện thương hiệu, bố cục website cần truyền tải được tính trẻ trung, thủ công và khả năng tiếp cận của thương hiệu đối với khách hàng trẻ. Việc sử dụng màu đỏ tại logo, nút kêu gọi hành động và nhãn thông tin, kết hợp với nền kem, hồng nhạt và vàng kem, tạo điều kiện làm nổi bật hình ảnh phụ kiện. Theo đó, bố cục cần ưu tiên ảnh sản phẩm thực tế, khoảng trắng hợp lý và hệ thống điều hướng rõ ràng trên cả máy tính lẫn thiết bị di động.":
        "Qua đánh giá nhận diện, bố cục Website cần thể hiện được đặc trưng trẻ trung, thủ công và phù hợp với nhóm khách hàng trẻ. Màu đỏ được sử dụng tại logo, nút kêu gọi hành động và nhãn thông tin; trong khi nền kem, hồng nhạt và vàng kem hỗ trợ làm nổi bật hình ảnh phụ kiện. Trên cơ sở đó, nhóm ưu tiên ảnh sản phẩm thực tế, khoảng trắng hợp lý và hệ thống điều hướng rõ ràng trên cả máy tính lẫn thiết bị di động.",
    "Qua quan sát cấu trúc đầu trang, logo, thanh tìm kiếm, thông tin đơn hàng, tài khoản và điều hướng được bố trí tại các vị trí có khả năng nhận biết cao. Cách tổ chức này giúp người dùng xác định nhanh chức năng của website, từ đó giảm số thao tác cần thiết khi tìm kiếm sản phẩm hoặc tiếp cận kênh tư vấn.":
        "Kết quả quan sát khu vực đầu trang cho thấy logo, thanh tìm kiếm, thông tin đơn hàng, tài khoản và thanh điều hướng được đặt ở các vị trí dễ nhận biết. Cách bố trí này hỗ trợ người dùng nhận diện nhanh chức năng của Website, qua đó rút ngắn thao tác khi tìm sản phẩm hoặc tiếp cận kênh tư vấn.",
    "Về điều hướng danh mục, việc phân nhóm thành tất cả sản phẩm, vòng tay, móc khóa, hộp quà và vòng cổ tạo cơ sở cho người dùng chuyển từ nhu cầu quà tặng sang trang sản phẩm phù hợp. Cấu trúc này góp phần hạn chế chi phí tìm kiếm thông tin và hỗ trợ quá trình ra quyết định.":
        "Về khả năng điều hướng, các sản phẩm được phân thành nhóm tất cả sản phẩm, vòng tay, móc khóa, hộp quà và vòng cổ. Cấu trúc này giúp người dùng chuyển từ nhu cầu quà tặng đến trang sản phẩm phù hợp, đồng thời giảm chi phí tìm kiếm thông tin trong quá trình ra quyết định.",
    "Hệ sinh thái nội dung gồm trang chủ, câu chuyện thương hiệu, tin tức, voucher, mini game và liên hệ tạo ra nhiều điểm chạm trước khi mua. Xét về chức năng, cấu trúc này hỗ trợ đồng thời ba mục tiêu: gia tăng nhận diện, cung cấp thông tin và thúc đẩy chuyển đổi.":
        "Hệ thống nội dung trên Website bao gồm trang chủ, câu chuyện thương hiệu, tin tức, voucher, mini game và liên hệ, qua đó hình thành nhiều điểm chạm trước khi mua. Xét theo chức năng, cấu trúc này đồng thời hỗ trợ gia tăng nhận diện, cung cấp thông tin và thúc đẩy chuyển đổi.",
    "Tại khu vực mở đầu, nội dung cần tập trung vào phụ kiện handmade, giá trị quà tặng và câu chuyện của từng sản phẩm. Việc điều hướng ưu tiên đến vòng tay, móc khóa hoặc hộp quà giúp giảm sự phân tán lựa chọn trên màn hình đầu và tăng tính rõ ràng của thông điệp.":
        "Tại khu vực mở đầu, nhóm tập trung thể hiện phụ kiện handmade, giá trị quà tặng và câu chuyện gắn với từng sản phẩm. Việc ưu tiên điều hướng đến vòng tay, móc khóa hoặc hộp quà giúp hạn chế sự phân tán lựa chọn trên màn hình đầu và làm rõ thông điệp của thương hiệu.",
    "Xét theo hành trình người dùng, trang chủ được tổ chức theo trình tự nhận biết thương hiệu, lựa chọn danh mục, xem sản phẩm nổi bật, tìm hiểu câu chuyện và tiếp nhận gợi ý quà tặng theo dịp. Các điểm điều hướng tiếp theo đến voucher, bài viết, trang sản phẩm hoặc liên hệ tạo ra mạch thông tin liên tục. Cách tổ chức này phù hợp với đặc điểm mua phụ kiện chịu ảnh hưởng của cảm xúc nhưng vẫn đòi hỏi thông tin xác nhận về chất lượng và độ tin cậy.":
        "Qua phân tích hành trình người dùng, trang chủ được sắp xếp theo trình tự từ nhận biết thương hiệu, lựa chọn danh mục, xem sản phẩm nổi bật đến tìm hiểu câu chuyện và tham khảo gợi ý quà tặng theo dịp. Các liên kết đến voucher, bài viết, trang sản phẩm hoặc kênh liên hệ duy trì mạch thông tin liên tục. Cách tổ chức này phù hợp với hành vi mua phụ kiện chịu tác động của cảm xúc, đồng thời cung cấp thông tin để khách hàng đánh giá chất lượng và độ tin cậy.",
    "Việc trình bày danh mục theo hướng trực quan giúp rút ngắn thời gian tìm kiếm và tạo lối tiếp cận nhanh đến các nhóm sản phẩm có nhu cầu cao.":
        "Kết quả đánh giá cho thấy cách trình bày danh mục trực quan hỗ trợ rút ngắn thời gian tìm kiếm và giúp người dùng tiếp cận nhanh các nhóm sản phẩm có nhu cầu cao.",
    "Các thẻ danh mục được xem là điểm trung gian giữa trang chủ và danh sách sản phẩm. Do đó, ảnh đại diện đồng bộ, tên gọi ngắn gọn, nút 'Khám phá' và mô tả bám sát ý định tìm kiếm là các yếu tố cần được chuẩn hóa để nâng cao khả năng điều hướng.":
        "Các thẻ danh mục giữ vai trò kết nối trang chủ với danh sách sản phẩm. Để nâng cao khả năng điều hướng, nhóm cần chuẩn hóa ảnh đại diện, sử dụng tên gọi ngắn gọn, duy trì nút 'Khám phá' và xây dựng mô tả phù hợp với ý định tìm kiếm.",
    "Dưới góc độ khả năng tìm kiếm, mỗi danh mục cần có đường dẫn riêng, tiêu đề trang, mô tả meta và phần giới thiệu ngắn gọn. Việc liên kết đến bài viết và trang danh mục Hộp quà khi phù hợp giúp tăng cường liên kết nội bộ và hỗ trợ hiệu quả SEO.":
        "Xét về khả năng tìm kiếm, mỗi danh mục cần có đường dẫn riêng, tiêu đề trang, mô tả meta và phần giới thiệu ngắn gọn. Bên cạnh đó, liên kết đến bài viết và trang danh mục Hộp quà phù hợp sẽ tăng cường liên kết nội bộ và hỗ trợ hiệu quả SEO.",
    "Trang danh sách sản phẩm cần được đánh giá theo khả năng hỗ trợ người dùng duyệt nhóm và so sánh nhanh giữa các mẫu. Mỗi thẻ sản phẩm cần thể hiện ảnh thực tế, nhãn nhận diện, tên, giá, tình trạng còn hàng và nút xem chi tiết. Đối với nhóm hộp quà, cách trình bày theo dịp tặng có ý nghĩa trong việc giảm thời gian lựa chọn và làm rõ ngữ cảnh sử dụng.":
        "Trang danh sách sản phẩm được xem xét dựa trên khả năng hỗ trợ người dùng duyệt danh mục và so sánh các mẫu. Theo đó, mỗi thẻ sản phẩm cần thể hiện ảnh thực tế, nhãn nhận diện, tên, giá, tình trạng còn hàng và nút xem chi tiết. Riêng với nhóm hộp quà, cách sắp xếp theo dịp tặng giúp rút ngắn thời gian lựa chọn và làm rõ ngữ cảnh sử dụng.",
    "Độ minh bạch trong hiển thị giá cần được rà soát thông qua mức giảm giá và giá gạch ngang, nhằm bảo đảm thông tin dễ hiểu và không tạo cảm nhận thiếu nhất quán với giá trị thủ công của thương hiệu.":
        "Về thông tin giá, nhóm cần rà soát cách thể hiện mức giảm giá và giá gạch ngang. Việc trình bày minh bạch giúp khách hàng dễ tiếp nhận thông tin, đồng thời duy trì sự nhất quán với giá trị thủ công của thương hiệu.",
    "Việc chuẩn hóa ảnh sản phẩm theo tỷ lệ 3:4, đặt sản phẩm trên nền vàng kem và duy trì tỷ lệ hiển thị khoảng 60-70% khung hình tạo ra tính nhất quán thị giác giữa danh mục sản phẩm và trang danh mục Hộp quà.":
        "Về hình ảnh, quy chuẩn tỷ lệ 3:4, nền vàng kem và phần sản phẩm chiếm khoảng 60-70% khung hình được áp dụng nhằm tạo sự đồng bộ về thị giác giữa danh mục sản phẩm và trang danh mục Hộp quà.",
    "Tên sản phẩm cần được chuẩn hóa về chính tả, thể hiện đặc điểm phân biệt và tích hợp từ khóa theo cách tự nhiên để đồng thời hỗ trợ trải nghiệm đọc và khả năng tìm kiếm.":
        "Tên sản phẩm cần được kiểm soát về chính tả, nêu rõ đặc điểm phân biệt và lồng ghép từ khóa một cách tự nhiên. Quy chuẩn này vừa hỗ trợ trải nghiệm đọc, vừa tăng khả năng tìm kiếm.",
    "Trang chi tiết sản phẩm cần được đánh giá trên cơ sở mức độ đầy đủ của hình ảnh thực tế, nhãn handmade, giá, lựa chọn biến thể, số lượng, trạng thái còn hàng, chính sách liên quan và nút chuyển đổi. Các thành phần như đánh giá, sản phẩm liên quan và kênh tư vấn giúp người dùng có thêm căn cứ để xác định mức độ phù hợp trước khi đặt hàng.":
        "Nhóm đánh giá trang chi tiết sản phẩm dựa trên mức độ đầy đủ của hình ảnh thực tế, nhãn handmade, giá, lựa chọn biến thể, số lượng, trạng thái còn hàng, chính sách liên quan và nút chuyển đổi. Các thành phần đánh giá, sản phẩm liên quan và kênh tư vấn cung cấp thêm căn cứ để người dùng xác định mức độ phù hợp trước khi đặt hàng.",
    "Đối với hộp quà, trang chi tiết cần làm rõ dịp tặng phù hợp, thành phần gói quà, phương án đóng gói, chính sách giao hàng và cách thức liên hệ tư vấn. Trọng tâm thông tin nên đặt vào giá trị sử dụng và trải nghiệm tặng quà, thay vì bổ sung các thông số không có ý nghĩa trực tiếp đối với quyết định mua.":
        "Đối với hộp quà, nội dung chi tiết cần nêu rõ dịp tặng, thành phần gói quà, phương án đóng gói, chính sách giao hàng và cách liên hệ tư vấn. Trọng tâm đánh giá được đặt vào giá trị sử dụng và trải nghiệm tặng quà, thay cho các thông số không tác động trực tiếp đến quyết định mua.",
    "Các nội dung bổ sung như hướng dẫn chọn quà theo dịp, chính sách đổi trả và ảnh minh họa đóng gói thực tế có vai trò giảm bất cân xứng thông tin. Nhờ đó, quyết định của khách hàng được hình thành trên cơ sở thông tin rõ ràng thay vì chỉ dựa vào yếu tố hình ảnh.":
        "Các nội dung hướng dẫn chọn quà theo dịp, chính sách đổi trả và ảnh đóng gói thực tế có tác dụng bổ sung thông tin cho trang sản phẩm. Nhờ đó, khách hàng có thể đưa ra quyết định trên cơ sở thông tin rõ ràng, thay vì chỉ dựa vào hình ảnh.",
    "Dữ liệu có cấu trúc của sản phẩm cần bao gồm giá, tình trạng còn hàng, thương hiệu, hình ảnh và đánh giá khi có đủ dữ liệu. Việc triển khai các trường thông tin này hỗ trợ công cụ tìm kiếm hiểu rõ hơn nội dung của trang sản phẩm.":
        "Về dữ liệu có cấu trúc, trang sản phẩm cần khai báo giá, tình trạng còn hàng, thương hiệu, hình ảnh và đánh giá khi dữ liệu đã đầy đủ. Các trường thông tin này giúp công cụ tìm kiếm xác định rõ hơn nội dung của trang sản phẩm.",
    "Trang câu chuyện thương hiệu góp phần chuyển hóa nhận thức từ một điểm bán phụ kiện thành một thương hiệu có định vị và lý do tồn tại rõ ràng. Nội dung cần thể hiện nhất quán nguồn gốc hình thành từ tình yêu với sản phẩm handmade và mong muốn tạo ra những món quà có ý nghĩa; qua đó làm nổi bật giá trị thủ công, cảm xúc và sự chỉn chu.":
        "Trang câu chuyện thương hiệu giúp khách hàng nhận diện Mushroomie không chỉ là một điểm bán phụ kiện mà còn là thương hiệu có định vị rõ ràng. Nội dung được xây dựng nhất quán từ nguồn gốc hình thành, tình yêu dành cho sản phẩm handmade đến mong muốn tạo ra những món quà có ý nghĩa; qua đó làm rõ giá trị thủ công, cảm xúc và sự chỉn chu.",
    "Việc chuẩn hóa các mốc thời gian và dữ kiện nhận diện giữa website, báo cáo và các kênh truyền thông là điều kiện cần để bảo đảm tính nhất quán của hồ sơ thương hiệu, đồng thời hạn chế khả năng phát sinh mâu thuẫn thông tin trong quá trình nghiệm thu.":
        "Nhóm cần đồng bộ các mốc thời gian và dữ kiện nhận diện giữa Website, báo cáo và các kênh truyền thông. Yêu cầu này bảo đảm tính nhất quán của hồ sơ thương hiệu và hạn chế mâu thuẫn thông tin trong quá trình nghiệm thu.",
    "Xét về chức năng SEO, trang tin tức là điểm tiếp cận lưu lượng tự nhiên từ các truy vấn liên quan đến vòng tay handmade, phụ kiện handmade, móc khóa và hộp quà. Tại thời điểm kiểm tra, website hiển thị 66 bài viết, cho thấy nền tảng nội dung đã có độ phủ ban đầu. Tuy nhiên, chất lượng nội dung vẫn cần được kiểm soát theo các tiêu chí về tính độc nhất, chiều sâu chuyên môn, liên kết nội bộ và rủi ro lặp cấu trúc.":
        "Xét theo chức năng SEO, trang tin tức là điểm tiếp cận lưu lượng tự nhiên từ các truy vấn về vòng tay handmade, phụ kiện handmade, móc khóa và hộp quà. Tại thời điểm kiểm tra, Website hiển thị 66 bài viết, phản ánh độ phủ nội dung ban đầu. Tuy nhiên, nhóm vẫn cần kiểm soát tính độc nhất, chiều sâu chuyên môn, liên kết nội bộ và nguy cơ lặp cấu trúc để bảo đảm chất lượng nội dung.",
    "Tiêu đề bài viết cần phản ánh đúng ý định tìm kiếm và bảo đảm sự khác biệt giữa các chủ đề, qua đó hạn chế tình trạng tạo hàng loạt tiêu đề có cấu trúc tương đồng.":
        "Về tiêu đề bài viết, nội dung cần bám sát ý định tìm kiếm và thể hiện sự khác biệt giữa các chủ đề. Cách thực hiện này hạn chế việc xuất bản hàng loạt tiêu đề có cấu trúc tương đồng.",
    "Việc sử dụng ảnh bìa đồng bộ nhận diện, ảnh sản phẩm thực tế, liên kết đến danh mục hoặc trang danh mục Hộp quà và nút liên hệ cụ thể giúp nội dung SEO không chỉ tạo lưu lượng truy cập mà còn hỗ trợ chuyển đổi.":
        "Nhóm sử dụng ảnh bìa đồng bộ nhận diện, ảnh sản phẩm thực tế, liên kết đến danh mục hoặc trang danh mục Hộp quà và nút liên hệ cụ thể. Các thành phần này giúp nội dung SEO vừa tạo lưu lượng truy cập, vừa hỗ trợ chuyển đổi.",
    "Đối với nhóm bài SEO địa phương, tính xác thực của thông tin khu vực là tiêu chí quan trọng. Nội dung cần phản ánh bối cảnh địa phương thực tế, thay vì chỉ thay thế tên khu vực trong cùng một khuôn mẫu bài viết.":
        "Đối với bài SEO địa phương, nhóm xác định tính xác thực của thông tin khu vực là tiêu chí trọng yếu. Vì vậy, nội dung cần phản ánh bối cảnh địa phương thực tế và không chỉ thay tên khu vực trong cùng một khuôn mẫu bài viết.",
    "Giỏ hàng và thanh toán là các điểm tiếp xúc có ảnh hưởng trực tiếp đến hiệu quả chuyển đổi. Giao diện cần cho phép người dùng kiểm tra tên sản phẩm, số lượng, tạm tính, mã voucher, phí giao hàng và tổng thanh toán. Đối với hộp quà, thông tin về gói quà và kênh tư vấn cần được thể hiện rõ để giảm sai lệch giữa quá trình tư vấn và đơn hàng.":
        "Giỏ hàng và thanh toán là hai điểm tiếp xúc tác động trực tiếp đến hiệu quả chuyển đổi. Tại đây, người dùng cần kiểm tra được tên sản phẩm, số lượng, tạm tính, mã voucher, phí giao hàng và tổng thanh toán. Đối với hộp quà, việc làm rõ thông tin gói quà và kênh tư vấn giúp hạn chế sai lệch giữa nội dung tư vấn và đơn hàng.",
    "Việc tối giản số trường bắt buộc và sử dụng thông báo lỗi rõ ràng trên thiết bị di động góp phần giảm ma sát trong quá trình hoàn tất đơn hàng.":
        "Trên thiết bị di động, việc giảm các trường bắt buộc và hiển thị thông báo lỗi rõ ràng sẽ hạn chế trở ngại trong quá trình khách hàng hoàn tất đơn hàng.",
    "Trước bước xác nhận đơn hàng, chính sách đổi trả, phương thức thanh toán và kênh liên hệ hỗ trợ cần được trình bày ngắn gọn, đúng vị trí. Cách tổ chức này có tác dụng giảm khả năng khách hàng rời bỏ tại giai đoạn cuối của hành trình mua.":
        "Trước khi xác nhận đơn hàng, Website cần trình bày ngắn gọn và đúng vị trí các thông tin về chính sách đổi trả, phương thức thanh toán và kênh hỗ trợ. Cách tổ chức này góp phần hạn chế việc khách hàng rời bỏ ở giai đoạn cuối của hành trình mua.",
    "Hệ thống đo lường cần thiết lập các sự kiện add_to_cart, begin_thanh toán và purchase hoặc order_submit để tạo cơ sở đánh giá hành vi chuyển đổi.":
        "Về đo lường, nhóm cần thiết lập các sự kiện add_to_cart, begin_thanh toán và purchase hoặc order_submit. Dữ liệu từ các sự kiện này là cơ sở để đánh giá hành vi chuyển đổi.",
    "Trang thanh toán được tổ chức theo ba bước gồm giỏ hàng, thanh toán và hoàn tất. Khu vực biểu mẫu thu thập họ tên, thông tin liên hệ, địa chỉ giao hàng và ghi chú; trong khi khối tóm tắt đơn hàng thể hiện sản phẩm, tạm tính, phí vận chuyển, voucher và tổng thanh toán. Cách phân tách này giúp người dùng kiểm tra thông tin trước khi xác nhận và làm rõ hai phương thức thanh toán gồm chuyển khoản qua mã QR và thanh toán khi nhận hàng.":
        "Trang thanh toán được triển khai theo ba bước gồm giỏ hàng, thanh toán và hoàn tất. Biểu mẫu tiếp nhận họ tên, thông tin liên hệ, địa chỉ giao hàng và ghi chú; khối tóm tắt đơn hàng trình bày sản phẩm, tạm tính, phí vận chuyển, voucher và tổng thanh toán. Cấu trúc này hỗ trợ người dùng kiểm tra thông tin trước khi xác nhận, đồng thời phân biệt hai phương thức thanh toán gồm chuyển khoản qua mã QR và thanh toán khi nhận hàng.",
    "Chân trang tập hợp nhóm danh mục sản phẩm, câu chuyện thương hiệu, tin tức, voucher, mini game, chính sách giao hàng - đổi trả, bảo mật, điều khoản dịch vụ và thông tin liên hệ. Xét theo tiêu chí tin cậy, việc công khai địa chỉ, số điện thoại, email, tên miền và các kênh mạng xã hội tạo cơ sở để khách hàng kiểm chứng thông tin và tiếp tục tương tác sau khi rời trang.":
        "Chân trang tập hợp danh mục sản phẩm, câu chuyện thương hiệu, tin tức, voucher, mini game, chính sách giao hàng - đổi trả, bảo mật, điều khoản dịch vụ và thông tin liên hệ. Qua đánh giá tiêu chí tin cậy, việc công khai địa chỉ, số điện thoại, email, tên miền và các kênh mạng xã hội giúp khách hàng kiểm chứng thông tin và duy trì tương tác sau khi rời trang.",
    "Chân trang tập hợp các liên kết đến danh mục, câu chuyện thương hiệu, tin tức, voucher, mini game, liên hệ, chính sách giao hàng - đổi trả, bảo mật và điều khoản dịch vụ. Đồng thời, việc xây dựng các trang địa phương như 'Phụ kiện handmade Đồng Nai' và 'Hộp quà handmade Biên Hòa' hỗ trợ định hướng tiếp cận người dùng tại khu vực triển khai.":
        "Về cấu trúc liên kết, chân trang điều hướng đến danh mục, câu chuyện thương hiệu, tin tức, voucher, mini game, liên hệ, chính sách giao hàng - đổi trả, bảo mật và điều khoản dịch vụ. Bên cạnh đó, các trang địa phương như 'Phụ kiện handmade Đồng Nai' và 'Hộp quà handmade Biên Hòa' hỗ trợ tiếp cận người dùng tại khu vực triển khai.",
    "Tính nhất quán của thông tin liên hệ, số điện thoại, email và địa chỉ giữa website, Facebook, Instagram, TikTok, Shopee và báo cáo là yêu cầu cần thiết để củng cố độ tin cậy của thương hiệu.":
        "Nhóm cần bảo đảm thông tin liên hệ, số điện thoại, email và địa chỉ được trình bày nhất quán trên Website, Facebook, Instagram, TikTok, Shopee và báo cáo. Sự đồng bộ này là cơ sở củng cố độ tin cậy của thương hiệu.",
    "Trong trường hợp thương hiệu có điểm nhận hàng hoặc địa chỉ phục vụ khách hàng thực tế, Hồ sơ doanh nghiệp trên Google và bản đồ là các hạng mục cần được bổ sung để tăng khả năng kiểm chứng thông tin địa phương.":
        "Trường hợp Mushroomie có điểm nhận hàng hoặc địa chỉ phục vụ khách hàng thực tế, nhóm cần bổ sung Hồ sơ doanh nghiệp trên Google và bản đồ. Các hạng mục này hỗ trợ khách hàng kiểm chứng thông tin địa phương.",
    "Chính sách cần làm rõ điều kiện đổi trả đối với hộp quà và sản phẩm đóng gói sẵn. Việc trình bày minh bạch các điều kiện này vừa bảo vệ trải nghiệm khách hàng, vừa hỗ trợ nhóm vận hành xử lý thông tin theo cùng một chuẩn.":
        "Chính sách đổi trả cần quy định rõ điều kiện áp dụng cho hộp quà và sản phẩm đóng gói sẵn. Việc công khai các điều kiện này vừa bảo đảm trải nghiệm khách hàng, vừa giúp nhóm vận hành xử lý thông tin theo một quy chuẩn thống nhất.",
    "Đánh giá trải nghiệm di động cho thấy menu cần được thu gọn hợp lý; thẻ sản phẩm nên hiển thị theo một hoặc hai cột tùy kích thước màn hình; nút kêu gọi hành động cần có vùng chạm tối thiểu 44 px; nội dung không được tràn ngang và hình ảnh cần co giãn theo khung hiển thị. Các tiêu chí này đặc biệt quan trọng vì phần lớn lượt tiếp cận từ mạng xã hội diễn ra trên thiết bị di động.":
        "Qua đánh giá trải nghiệm di động, menu cần được thu gọn hợp lý; thẻ sản phẩm hiển thị theo một hoặc hai cột tùy kích thước màn hình; nút kêu gọi hành động có vùng chạm tối thiểu 44 px; nội dung không tràn ngang và hình ảnh co giãn theo khung hiển thị. Các tiêu chí này cần được ưu tiên do phần lớn lượt tiếp cận từ mạng xã hội diễn ra trên thiết bị di động.",
    "Trong giai đoạn triển khai nội dung, Mushroomie xây dựng quy chuẩn đăng sản phẩm nhằm duy trì tính nhất quán về nhận diện, khả năng tìm kiếm và trải nghiệm mua hàng. Mỗi sản phẩm cần có ảnh bìa, ảnh cận chi tiết, ảnh chất liệu hoặc quy trình và ảnh đóng gói thực tế. Phần mô tả tập trung vào chất liệu, cách chọn quà, hướng dẫn bảo quản, chính sách giao hàng - đổi trả và kênh liên hệ tư vấn.":
        "Trong giai đoạn triển khai nội dung, nhóm xây dựng quy chuẩn đăng sản phẩm cho Mushroomie nhằm duy trì sự nhất quán về nhận diện, khả năng tìm kiếm và trải nghiệm mua hàng. Mỗi sản phẩm được yêu cầu có ảnh bìa, ảnh cận chi tiết, ảnh chất liệu hoặc quy trình và ảnh đóng gói thực tế. Phần mô tả tập trung làm rõ chất liệu, cách chọn quà, hướng dẫn bảo quản, chính sách giao hàng - đổi trả và kênh liên hệ tư vấn.",
    "Kết quả PageSpeed Insights được ghi nhận trực tiếp sau khi báo cáo hoàn tất lúc 14:06:58 ngày 19/07/2026 trên phiên bản di động. Website đạt 97 điểm Hiệu suất, 96 điểm Hỗ trợ tiếp cận, 100 điểm Phương pháp hay nhất và 100 điểm SEO. Các chỉ số phòng thí nghiệm gồm FCP 1,5 giây, LCP 2,0 giây, TBT 160 mili giây, CLS 0 và Speed Index 1,5 giây. Đây là kết quả tại một thời điểm đo cụ thể, do đó cần được kiểm tra lại sau các thay đổi lớn về hình ảnh, giao diện hoặc mã nguồn.":
        "Kết quả PageSpeed Insights trên phiên bản di động được ghi nhận trực tiếp sau khi báo cáo hoàn tất lúc 14:06:58 ngày 19/07/2026. Website đạt 97 điểm Hiệu suất, 96 điểm Hỗ trợ tiếp cận, 100 điểm Phương pháp hay nhất và 100 điểm SEO; các chỉ số phòng thí nghiệm gồm FCP 1,5 giây, LCP 2,0 giây, TBT 160 mili giây, CLS 0 và Speed Index 1,5 giây. Dữ liệu phản ánh trạng thái Website tại một thời điểm đo cụ thể; vì vậy, nhóm cần kiểm tra lại sau các thay đổi lớn về hình ảnh, giao diện hoặc mã nguồn.",
    "Theo cấu trúc đánh giá của Google PageSpeed Insights và Lighthouse, kết quả được xem xét ở bốn nhóm gồm Hiệu suất, Hỗ trợ tiếp cận, Phương pháp hay nhất và SEO. Bài luận sử dụng trực tiếp các điểm số và chỉ số xuất hiện trên ảnh chụp của cùng một lần đo, qua đó bảo đảm sự thống nhất giữa dữ liệu định lượng và phần nhận xét học thuật.":
        "Theo cấu trúc của Google PageSpeed Insights và Lighthouse, nhóm đánh giá kết quả theo bốn nhóm gồm Hiệu suất, Hỗ trợ tiếp cận, Phương pháp hay nhất và SEO. Các điểm số và chỉ số trong bài luận được trích trực tiếp từ ảnh chụp của cùng một lần đo, qua đó bảo đảm sự thống nhất giữa dữ liệu định lượng và nội dung nhận xét.",
    "Kết quả đo trên máy tính ghi nhận FCP khoảng 0,4 giây, LCP khoảng 0,8 giây, TBT khoảng 30 mili giây và CLS 0,002. Các chỉ số này phản ánh khả năng phản hồi tốt của trang tại thời điểm đo. Tuy nhiên, việc đánh giá cần được lặp lại sau các thay đổi lớn về hình ảnh, giao diện hoặc mã nguồn để theo dõi nguy cơ suy giảm hiệu suất theo thời gian.":
        "Trên máy tính, kết quả ghi nhận FCP khoảng 0,4 giây, LCP khoảng 0,8 giây, TBT khoảng 30 mili giây và CLS 0,002. Các chỉ số cho thấy trang có khả năng phản hồi tốt tại thời điểm đo. Tuy nhiên, nhóm cần lặp lại phép đo sau các thay đổi lớn về hình ảnh, giao diện hoặc mã nguồn để theo dõi nguy cơ suy giảm hiệu suất theo thời gian.",
    "Phân tích tài nguyên cho thấy ảnh đầu trang, ảnh sản phẩm và ảnh trên trang danh mục Hộp quà là các thành phần có khả năng tác động trực tiếp đến LCP; vì vậy, các tài nguyên này cần được ưu tiên trong quá trình tối ưu.":
        "Qua phân tích tài nguyên, ảnh đầu trang, ảnh sản phẩm và ảnh trên trang danh mục Hộp quà là các thành phần có thể tác động trực tiếp đến LCP. Do đó, nhóm cần ưu tiên các tài nguyên này trong quá trình tối ưu.",
    "Việc giảm CSS/JS không sử dụng, trì hoãn các script không cần thiết cho màn hình đầu và kiểm soát thư viện bên thứ ba là các hướng can thiệp phù hợp để hạn chế tải trọng ban đầu.":
        "Về mã nguồn, hướng xử lý phù hợp là giảm CSS/JS không sử dụng, trì hoãn các script không cần thiết cho màn hình đầu và kiểm soát thư viện bên thứ ba. Các biện pháp này giúp hạn chế tải trọng ban đầu.",
    "Ở phương diện hạ tầng, bộ nhớ đệm, nén và CDN cần được xem xét theo điều kiện triển khai thực tế. Đồng thời, việc sử dụng tỷ lệ ảnh phù hợp với khung hiển thị góp phần giảm dung lượng tải ở giai đoạn đầu.":
        "Ở phương diện hạ tầng, nhóm cần xem xét bộ nhớ đệm, nén và CDN theo điều kiện triển khai thực tế. Đồng thời, việc sử dụng tỷ lệ ảnh phù hợp với khung hiển thị sẽ giảm dung lượng tải ở giai đoạn đầu.",
    "Mức độ phức tạp của DOM và các component lặp trên trang chủ cần được theo dõi định kỳ, vì đây là các yếu tố có thể ảnh hưởng đến tốc độ hiển thị và khả năng duy trì hiệu suất.":
        "Bên cạnh đó, nhóm cần theo dõi định kỳ mức độ phức tạp của DOM và các component lặp trên trang chủ. Đây là những yếu tố có thể ảnh hưởng đến tốc độ hiển thị và khả năng duy trì hiệu suất.",
    "Ở lần đo lúc 12:41 ngày 19/07/2026, phiên bản di động ghi nhận FCP khoảng 1,5 giây, LCP khoảng 2,0 giây, TBT khoảng 120 mili giây và CLS bằng 0. Lần đo cập nhật lúc 14:06:58 ghi nhận TBT 160 mili giây, cho thấy chỉ số có thể dao động theo điều kiện đo và trạng thái tài nguyên; vì vậy, kết quả cần được theo dõi theo chuỗi thời gian thay vì diễn giải từ một lần kiểm tra đơn lẻ.":
        "Tại lần đo lúc 12:41 ngày 19/07/2026, phiên bản di động ghi nhận FCP khoảng 1,5 giây, LCP khoảng 2,0 giây, TBT khoảng 120 mili giây và CLS bằng 0. Ở lần đo cập nhật lúc 14:06:58, TBT được ghi nhận ở mức 160 mili giây, phản ánh sự dao động theo điều kiện đo và trạng thái tài nguyên. Vì vậy, nhóm cần theo dõi kết quả theo chuỗi thời gian thay vì kết luận từ một lần kiểm tra đơn lẻ.",
    "Trên thiết bị di động, việc giảm ảnh và tài nguyên tải ban đầu, đồng thời ưu tiên nội dung, ảnh sản phẩm thực tế và nút liên hệ tại khu vực phía trên màn hình, là hướng tối ưu cần được duy trì.":
        "Đối với thiết bị di động, nhóm cần tiếp tục giảm ảnh và tài nguyên tải ban đầu, đồng thời ưu tiên nội dung, ảnh sản phẩm thực tế và nút liên hệ ở khu vực phía trên màn hình. Đây là hướng tối ưu trọng tâm cho trải nghiệm di động.",
    "Biểu mẫu liên hệ và thanh toán cần được kiểm tra để bảo đảm không bị bàn phím che khuất; các trường nhập cần sử dụng loại dữ liệu phù hợp và thông báo lỗi dễ hiểu nhằm hạn chế sai sót khi thao tác.":
        "Nhóm cần kiểm tra biểu mẫu liên hệ và thanh toán để tránh tình trạng bàn phím che khuất nội dung. Các trường nhập cần sử dụng loại dữ liệu phù hợp và thông báo lỗi dễ hiểu, qua đó hạn chế sai sót khi thao tác.",
    "Các thành phần như pop-up, chat hoặc thanh sticky cần được kiểm soát để không che khuất nút mua, tổng tiền hoặc nội dung sản phẩm, qua đó bảo đảm tính liên tục của hành trình chuyển đổi.":
        "Các thành phần pop-up, chat hoặc thanh sticky cần được kiểm soát để không che nút mua, tổng tiền hoặc nội dung sản phẩm. Việc kiểm soát này góp phần duy trì tính liên tục của hành trình chuyển đổi.",
    "Bên cạnh điểm tổng quan, việc đánh giá cần đi sâu vào từng nhóm tài nguyên có khả năng tác động đến khả năng hiển thị. Bảng sau tổng hợp chỉ số máy tính của lần đo 12:41 và chỉ số di động cập nhật lúc 14:06:58 ngày 19/07/2026; các mức tiết kiệm dung lượng chỉ được kết luận khi có ảnh chụp chẩn đoán tương ứng từ công cụ PageSpeed Insights.":
        "Bên cạnh điểm tổng quan, nhóm phân tích từng nhóm tài nguyên có thể tác động đến khả năng hiển thị. Bảng sau tổng hợp chỉ số máy tính của lần đo 12:41 và chỉ số di động cập nhật lúc 14:06:58 ngày 19/07/2026. Các mức tiết kiệm dung lượng chỉ được ghi nhận khi có ảnh chụp chẩn đoán tương ứng từ công cụ PageSpeed Insights.",
    "Qua rà soát công khai, website đã sử dụng HTTPS; tiêu đề và H1 phản ánh định vị phụ kiện handmade; đồng thời có menu điều hướng, danh mục sản phẩm, nội dung thương hiệu, trang tin tức và các trang SEO địa phương. Các hạng mục cần tiếp tục kiểm chứng bằng công cụ chuyên dụng gồm sitemap, robots.txt, canonical, trạng thái lập chỉ mục, dữ liệu có cấu trúc, lỗi 404 và báo cáo Google Search Console.":
        "Kết quả rà soát công khai cho thấy Website đã sử dụng HTTPS; tiêu đề và H1 thể hiện định vị phụ kiện handmade; đồng thời hệ thống có menu điều hướng, danh mục sản phẩm, nội dung thương hiệu, trang tin tức và các trang SEO địa phương. Tuy nhiên, sitemap, robots.txt, canonical, trạng thái lập chỉ mục, dữ liệu có cấu trúc, lỗi 404 và báo cáo Google Search Console vẫn cần được kiểm chứng bằng công cụ chuyên dụng.",
    "Báo cáo được thực hiện trực tiếp trên Google PageSpeed Insights đối với URL https://mushroomie.io.vn/ và hoàn tất lúc 14:06:58 ngày 19/07/2026. Ở chế độ di động, website đạt 100/100 điểm SEO; đồng thời đạt 97 điểm Hiệu suất, 96 điểm Hỗ trợ tiếp cận và 100 điểm Phương pháp hay nhất. Kết quả cho thấy trang chủ đáp ứng tốt nhóm yêu cầu SEO cơ bản mà Lighthouse có thể kiểm tra tự động tại thời điểm đo.":
        "Nhóm thực hiện báo cáo trực tiếp trên Google PageSpeed Insights cho URL https://mushroomie.io.vn/ và hoàn tất lúc 14:06:58 ngày 19/07/2026. Ở chế độ di động, Website đạt 100/100 điểm SEO, 97 điểm Hiệu suất, 96 điểm Hỗ trợ tiếp cận và 100 điểm Phương pháp hay nhất. Kết quả ghi nhận cho thấy trang chủ đáp ứng tốt các yêu cầu SEO cơ bản mà Lighthouse có thể kiểm tra tự động tại thời điểm đo.",
    "Trong nhóm SEO, Lighthouse ghi nhận 10 hoạt động kiểm tra tự động đạt yêu cầu. Công cụ đồng thời xác định một hạng mục cần kiểm tra thủ công và cho biết dữ liệu có cấu trúc hợp lệ. Các bằng chứng này hỗ trợ kết luận rằng nền tảng kỹ thuật SEO Onpage của trang chủ đang ở trạng thái tích cực; tuy nhiên, việc đạt 100 điểm không đồng nghĩa toàn bộ hoạt động SEO đã hoàn thiện.":
        "Trong nhóm SEO, Lighthouse ghi nhận 10 hoạt động kiểm tra tự động đạt yêu cầu. Công cụ cũng xác định một hạng mục cần kiểm tra thủ công và ghi nhận dữ liệu có cấu trúc hợp lệ. Dữ liệu này cho thấy nền tảng kỹ thuật SEO Onpage của trang chủ đang ở mức tích cực; tuy nhiên, kết quả 100 điểm không phản ánh toàn bộ hoạt động SEO đã hoàn thiện.",
    "Phạm vi Lighthouse tập trung vào các thực hành SEO kỹ thuật cơ bản và không thay thế việc đánh giá thứ hạng từ khóa, chất lượng nội dung, độ bao phủ lập chỉ mục, hồ sơ liên kết hoặc mức độ đáp ứng ý định tìm kiếm. Vì vậy, kết quả cần được đối chiếu thêm bằng Google Search Console, kiểm tra thủ công tiêu đề - mô tả meta - heading - liên kết nội bộ và theo dõi truy vấn thực tế sau khi nội dung được xuất bản.":
        "Lighthouse chỉ đánh giá các thực hành SEO kỹ thuật cơ bản, không thay thế việc xem xét thứ hạng từ khóa, chất lượng nội dung, độ bao phủ lập chỉ mục, hồ sơ liên kết hoặc mức độ đáp ứng ý định tìm kiếm. Vì vậy, nhóm cần đối chiếu kết quả bằng Google Search Console, kiểm tra thủ công tiêu đề - mô tả meta - heading - liên kết nội bộ và theo dõi truy vấn thực tế sau khi xuất bản nội dung.",
    "Kết luận phân tích cho thấy Website Mushroomie đã hình thành nền tảng SEO Onpage tốt ở cấp độ kỹ thuật cơ bản. Trọng tâm cải thiện tiếp theo là xử lý vấn đề tương phản đang làm điểm Hỗ trợ tiếp cận dừng ở mức 96, duy trì chất lượng dữ liệu có cấu trúc, kiểm tra trạng thái lập chỉ mục và đánh giá nội dung theo hiệu quả tiếp cận - chuyển đổi thay vì chỉ dựa trên điểm số công cụ.":
        "Từ kết quả phân tích, Website Mushroomie đã hình thành nền tảng SEO Onpage tích cực ở cấp độ kỹ thuật cơ bản. Trong giai đoạn tiếp theo, nhóm cần xử lý vấn đề tương phản khiến điểm Hỗ trợ tiếp cận dừng ở mức 96, duy trì chất lượng dữ liệu có cấu trúc, kiểm tra trạng thái lập chỉ mục và đánh giá nội dung theo hiệu quả tiếp cận - chuyển đổi thay vì chỉ dựa trên điểm số công cụ.",
    "Trong giai đoạn này, website được phát triển theo định hướng SEO và mở rộng độ phủ tự nhiên thông qua bộ từ khóa, bài viết chuyên đề và các điểm liên kết hỗ trợ. Cách tiếp cận này nhằm tăng khả năng tiếp cận truy vấn phù hợp mà vẫn duy trì sự liên kết giữa nội dung và trang đích.":
        "Trong giai đoạn này, nhóm phát triển Website theo định hướng SEO thông qua bộ từ khóa, bài viết chuyên đề và các điểm liên kết hỗ trợ. Cách triển khai này nhằm mở rộng độ phủ tự nhiên, tăng khả năng tiếp cận truy vấn phù hợp và duy trì mối liên hệ giữa nội dung với trang đích.",
    "Bộ từ khóa được tổ chức thành bốn nhóm gồm từ khóa sản phẩm, từ khóa hộp quà, từ khóa quà tặng theo nhu cầu và từ khóa địa phương. Quy trình lựa chọn được đánh giá đồng thời theo mức độ phù hợp với danh mục, ý định tìm kiếm, tiềm năng chuyển đổi và nguồn lực sản xuất nội dung của Mushroomie.":
        "Nhóm phân loại bộ từ khóa thành bốn nhóm gồm từ khóa sản phẩm, từ khóa hộp quà, từ khóa quà tặng theo nhu cầu và từ khóa địa phương. Mỗi từ khóa được xem xét theo mức độ phù hợp với danh mục, ý định tìm kiếm, tiềm năng chuyển đổi và nguồn lực sản xuất nội dung của Mushroomie.",
    "Quy trình xây dựng bộ từ khóa được tổ chức thành tám bước liên hoàn nhằm bảo đảm mối liên hệ giữa nhu cầu tìm kiếm, nội dung và trang đích. Cách tiếp cận này hạn chế việc lựa chọn từ khóa theo cảm tính và tạo cơ sở cho hoạt động theo dõi sau xuất bản.":
        "Quy trình xây dựng bộ từ khóa gồm tám bước liên hoàn, qua đó kết nối nhu cầu tìm kiếm với nội dung và trang đích. Cách tiếp cận có hệ thống này giúp hạn chế lựa chọn từ khóa theo cảm tính, đồng thời tạo cơ sở cho hoạt động theo dõi sau xuất bản.",
    "Mỗi bài viết SEO cần phục vụ một ý định tìm kiếm xác định và được liên kết với sản phẩm, danh mục hoặc trang danh mục Hộp quà phù hợp. Nội dung cần giải quyết câu hỏi thực tế của người đọc, phản ánh kiến thức về phụ kiện handmade, sử dụng hình ảnh sản phẩm thực tế và tránh mô hình bài viết chỉ thay thế từ khóa. Các thành phần được kiểm soát gồm tiêu đề, đường dẫn rút gọn, mô tả meta, heading, hình ảnh, liên kết nội bộ, nút kêu gọi hành động và dữ liệu có cấu trúc Article.":
        "Mỗi bài SEO được xây dựng cho một ý định tìm kiếm xác định và liên kết với sản phẩm, danh mục hoặc trang danh mục Hộp quà phù hợp. Nội dung cần giải đáp vấn đề thực tế của người đọc, thể hiện kiến thức về phụ kiện handmade, sử dụng hình ảnh sản phẩm thực tế và tránh cách viết chỉ thay thế từ khóa. Nhóm kiểm soát các thành phần gồm tiêu đề, đường dẫn rút gọn, mô tả meta, heading, hình ảnh, liên kết nội bộ, nút kêu gọi hành động và dữ liệu có cấu trúc Article.",
    "Để bảo đảm khả năng kiểm chứng, nhóm thực hiện cần lưu ảnh chụp màn hình của từng bài viết, bao gồm trang biên tập, tiêu đề và mô tả meta, kết quả đánh giá SEO, trạng thái lập chỉ mục trên Google Search Console và trang bài viết công khai. Minh chứng nên được lưu theo tên từ khóa để thuận tiện cho việc đối chiếu và đánh giá sau triển khai.":
        "Để bảo đảm khả năng kiểm chứng, nhóm cần lưu ảnh chụp màn hình của từng bài viết, bao gồm trang biên tập, tiêu đề và mô tả meta, kết quả đánh giá SEO, trạng thái lập chỉ mục trên Google Search Console và trang bài viết công khai. Việc lưu minh chứng theo tên từ khóa giúp nhóm thuận tiện đối chiếu và đánh giá sau triển khai.",
    "Bài mẫu sử dụng điểm Rank Math để minh họa mức độ hoàn thiện của bài viết trên WordPress. Website Mushroomie được phát triển trên nền tảng Next.js và không sử dụng Rank Math, vì vậy bài luận không sao chép hoặc quy đổi điểm của công cụ này. Tiêu chí đánh giá tương đương gồm tiêu đề, mô tả meta, URL, heading, nội dung đáp ứng ý định tìm kiếm, alt ảnh, liên kết nội bộ, dữ liệu Article, trạng thái lập chỉ mục và trang bài viết công khai. Mỗi bài chỉ được ghi nhận là hoàn thiện khi có đủ minh chứng cho các tiêu chí trên.":
        "Trong bài mẫu, điểm Rank Math được dùng để minh họa mức độ hoàn thiện của bài viết trên WordPress. Tuy nhiên, Website Mushroomie được phát triển bằng Next.js và không sử dụng Rank Math, do đó nhóm không sao chép hoặc quy đổi điểm của công cụ này. Các tiêu chí đánh giá tương đương bao gồm tiêu đề, mô tả meta, URL, heading, nội dung đáp ứng ý định tìm kiếm, alt ảnh, liên kết nội bộ, dữ liệu Article, trạng thái lập chỉ mục và trang bài viết công khai. Mỗi bài chỉ được ghi nhận hoàn thiện khi có đủ minh chứng cho các tiêu chí này.",
    "Liên kết ngược được triển khai theo nguyên tắc liên quan, minh bạch và ưu tiên chất lượng hơn số lượng. Giai đoạn đầu tập trung vào các nguồn có thể kiểm soát như hồ sơ mạng xã hội, sàn thương mại điện tử, Hồ sơ doanh nghiệp trên Google, Pinterest, bài cộng tác và nguồn địa phương. Việc không sử dụng hệ thống liên kết rác, mua liên kết số lượng lớn hoặc lặp văn bản liên kết quá mức giúp hạn chế rủi ro SEO.":
        "Nhóm triển khai liên kết ngược theo nguyên tắc liên quan, minh bạch và ưu tiên chất lượng thay vì số lượng. Trong giai đoạn đầu, các nguồn có khả năng kiểm soát được ưu tiên, bao gồm hồ sơ mạng xã hội, sàn thương mại điện tử, Hồ sơ doanh nghiệp trên Google, Pinterest, bài cộng tác và nguồn địa phương. Để hạn chế rủi ro SEO, nhóm không sử dụng hệ thống liên kết rác, mua liên kết số lượng lớn hoặc lặp văn bản liên kết quá mức.",
    "Trong giai đoạn chạy quảng cáo, quảng cáo tìm kiếm Google được xem là công cụ hỗ trợ điều hướng lưu lượng truy cập về website theo ngân sách đã phân bổ. Việc lựa chọn truy vấn có ý định mua hộp quà hoặc quà tặng handmade và dẫn về trang danh mục Hộp quà, thay vì mặc định về trang chủ, tạo điều kiện nâng cao mức độ phù hợp giữa nhu cầu tìm kiếm và nội dung trang đích.":
        "Trong giai đoạn chạy quảng cáo, nhóm sử dụng quảng cáo tìm kiếm Google để hỗ trợ điều hướng lưu lượng truy cập về Website trong phạm vi ngân sách đã phân bổ. Các truy vấn có ý định mua hộp quà hoặc quà tặng handmade được dẫn đến trang danh mục Hộp quà thay vì mặc định về trang chủ. Cách triển khai này làm tăng mức độ phù hợp giữa nhu cầu tìm kiếm và nội dung trang đích.",
    "Trước khi triển khai quảng cáo, hệ thống theo dõi bằng Google Analytics 4 và Google Ads cần được hoàn thiện; đồng thời cần kiểm tra trang cảm ơn hoặc sự kiện xác nhận đơn, gắn UTM cho các chiến dịch từ Facebook/Instagram và loại trừ các truy vấn không liên quan. Kết quả quảng cáo chỉ nên được kết luận khi có dữ liệu tài khoản và ảnh chụp minh chứng tương ứng.":
        "Trước khi chạy quảng cáo, nhóm cần hoàn thiện hệ thống theo dõi bằng Google Analytics 4 và Google Ads; kiểm tra trang cảm ơn hoặc sự kiện xác nhận đơn; gắn UTM cho các chiến dịch từ Facebook/Instagram và loại trừ truy vấn không liên quan. Kết quả quảng cáo chỉ được đánh giá khi có dữ liệu tài khoản và ảnh chụp minh chứng tương ứng.",
    "Trong giai đoạn tổng hợp và đánh giá, nhóm thực hiện đối chiếu lượt truy cập, người dùng mới, số trang đã xem, lượt nhấp CTA, lượt nhắn tin tư vấn, lượt chuyển hướng sang Shopee/Fanpage và đơn hàng phát sinh. Website đồng thời được rà soát về giao diện bán hàng, danh mục Hộp quà, nội dung SEO, trang danh mục, tối ưu kỹ thuật, liên kết hỗ trợ và quảng cáo tìm kiếm để xác định các hạng mục cần duy trì và ưu tiên cải thiện cho chiến dịch tiếp theo.":
        "Trong giai đoạn tổng hợp và đánh giá, nhóm đối chiếu lượt truy cập, người dùng mới, số trang đã xem, lượt nhấp CTA, lượt nhắn tin tư vấn, lượt chuyển hướng sang Shopee/Fanpage và đơn hàng phát sinh. Nhóm cũng rà soát Website theo các hạng mục giao diện bán hàng, danh mục Hộp quà, nội dung SEO, trang danh mục, tối ưu kỹ thuật, liên kết hỗ trợ và quảng cáo tìm kiếm. Kết quả đối chiếu là cơ sở xác định nội dung cần duy trì và ưu tiên cải thiện cho chiến dịch tiếp theo.",
    "Kết quả PageSpeed Insights trong báo cáo được ghi nhận từ lần đo thực tế ngày 19/07/2026 sau khi báo cáo hoàn tất. Các chỉ số Google Search Console, Google Ads và liên kết ngược chỉ được đưa vào phần đánh giá khi có dữ liệu nguồn và ảnh chụp minh chứng tương ứng. Cách tiếp cận này bảo đảm tính trung thực, khả năng kiểm chứng và phù hợp với yêu cầu của một bài luận tốt nghiệp.":
        "Dữ liệu PageSpeed Insights trong báo cáo được lấy từ lần đo thực tế ngày 19/07/2026 sau khi báo cáo hoàn tất. Đối với Google Search Console, Google Ads và liên kết ngược, nhóm chỉ đánh giá khi có dữ liệu nguồn và ảnh chụp minh chứng tương ứng. Cách thực hiện này bảo đảm tính trung thực, khả năng kiểm chứng và phù hợp với yêu cầu của bài luận tốt nghiệp.",
    "Tổng hợp các kết quả cho thấy Website Mushroomie đã hình thành tương đối đầy đủ chuỗi chức năng từ nhận diện thương hiệu, trưng bày sản phẩm, nội dung SEO, trang danh mục, giỏ hàng, thanh toán đến hỗ trợ sau bán. Ưu điểm nổi bật là giao diện đồng bộ với nhận diện, hình ảnh sản phẩm thực tế và hiệu suất tại thời điểm đo đạt mức tích cực. Hạn chế còn lại nằm ở việc cần kiểm chứng sâu hơn dữ liệu SEO, chất lượng nội dung, hệ thống đo lường chuyển đổi và kết quả quảng cáo. Vì vậy, giai đoạn tiếp theo cần ưu tiên chuẩn hóa minh chứng, theo dõi Google Search Console và Google Analytics 4, duy trì kiểm tra PageSpeed sau mỗi thay đổi lớn và đánh giá nội dung theo khả năng hỗ trợ chuyển đổi thay vì chỉ dựa trên số lượng xuất bản.":
        "Kết quả tổng hợp cho thấy Website Mushroomie đã hình thành tương đối đầy đủ chuỗi chức năng, từ nhận diện thương hiệu, trưng bày sản phẩm, nội dung SEO, trang danh mục, giỏ hàng, thanh toán đến hỗ trợ sau bán. Ưu điểm của kênh là giao diện đồng bộ với nhận diện, hình ảnh sản phẩm thực tế và hiệu suất ở mức tích cực tại thời điểm đo. Tuy nhiên, dữ liệu SEO, chất lượng nội dung, hệ thống đo lường chuyển đổi và kết quả quảng cáo vẫn cần được kiểm chứng sâu hơn. Trong giai đoạn tiếp theo, nhóm cần ưu tiên chuẩn hóa minh chứng, theo dõi Google Search Console và Google Analytics 4, duy trì kiểm tra PageSpeed sau mỗi thay đổi lớn và đánh giá nội dung theo khả năng hỗ trợ chuyển đổi thay vì chỉ dựa trên số lượng xuất bản.",
}


TABLE_CELL_REWRITES: dict[str, str] = {
    "Không bổ sung JavaScript hoặc thư viện bên thứ ba nặng nế nếu không cần thiết.":
        "Không bổ sung JavaScript hoặc thư viện bên thứ ba nặng nếu không cần thiết.",
    "Khả năng hiển thị nội dung đầu tiên tốt.":
        "Chỉ số phản ánh khả năng hiển thị nội dung đầu tiên ở mức tích cực tại thời điểm đo.",
    "Đạt ngưỡng trải nghiệm tốt tại thời điểm đo.":
        "Kết quả ghi nhận nằm trong ngưỡng trải nghiệm tốt tại thời điểm đo.",
    "Thời gian chặn thấp, tương tác ổn định.":
        "Chỉ số cho thấy thời gian chặn ở mức thấp và khả năng tương tác ổn định.",
    "Bố cục gần như không dịch chuyển khi tải.":
        "Kết quả phản ánh bố cục hầu như không dịch chuyển trong quá trình tải.",
    "Ảnh minh chứng hiện tại không thể hiện rõ giá trị để kết luận.":
        "Minh chứng hiện có chưa thể hiện rõ giá trị, do đó chưa đủ cơ sở để kết luận.",
    "Nội dung đầu tiên hiển thị trong ngưỡng tích cực.":
        "Chỉ số ghi nhận nội dung đầu tiên hiển thị trong ngưỡng tích cực.",
    "Đạt chuẩn tốt nhưng nhạy cảm với ảnh lớn và kết nối chậm.":
        "Kết quả đạt chuẩn tốt, tuy nhiên vẫn có thể bị tác động bởi ảnh lớn và kết nối chậm.",
    "Vẫn ở ngưỡng chấp nhận; cần theo dõi khi bổ sung tính năng.":
        "Chỉ số vẫn nằm trong ngưỡng chấp nhận và cần được theo dõi khi bổ sung tính năng.",
    "Không ghi nhận dịch chuyển bố cục.":
        "Kết quả đo không ghi nhận hiện tượng dịch chuyển bố cục.",
    "Tốc độ hoàn thiện phần nội dung nhìn thấy đạt mức tích cực trong điều kiện mô phỏng.":
        "Trong điều kiện mô phỏng, tốc độ hoàn thiện phần nội dung nhìn thấy được ghi nhận ở mức tích cực.",
    "Là nhóm rủi ro cần kiểm tra khi bundle hoặc giao diện được mở rộng.":
        "Đây là nhóm rủi ro cần được kiểm tra khi bundle hoặc giao diện được mở rộng.",
    "Có thể làm chậm nội dung đầu tiên nếu CSS hoặc script tải sớm quá mức.":
        "CSS hoặc script tải sớm quá mức có thể làm chậm thời điểm hiển thị nội dung đầu tiên.",
    "Ảnh banner hoặc ảnh sản phẩm đầu trang quyết định phần lớn thời gian LCP.":
        "Kết quả phân tích xác định ảnh banner hoặc ảnh sản phẩm đầu trang là yếu tố tác động lớn đến thời gian LCP.",
    "Ảnh tải lớn hơn khung hiển thị làm tăng dung lượng truyền không cần thiết.":
        "Việc tải ảnh lớn hơn khung hiển thị làm phát sinh dung lượng truyền không cần thiết.",
    "Chính sách cache không phù hợp làm tăng chi phí tải lại tài nguyên.":
        "Chính sách cache chưa phù hợp có thể làm tăng chi phí tải lại tài nguyên.",
    "Cấu trúc lồng nhau hoặc component lặp quá nhiều có thể tác động đến hiển thị và tương tác.":
        "Cấu trúc lồng nhau hoặc component lặp với số lượng lớn có thể ảnh hưởng đến khả năng hiển thị và tương tác.",
}
